# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D1ub2Oawn/i0mddyIezgAM3gbJSrqTND9Bdl+P1MT/Yn17EJQVWwMo7kP5ATdPHb7NIjMmuSsA4iPFmr53gC5Y7ivC5Rg+Rjed8rC+fx0xg3Ynnekp8BB3WFK44nSjiRgfZWfaw1FkKaj5e1dxnAuFwSRgt79utjaZ7A5pfEdWBalLtcnxt2dLiChmQle+2jiRHzGHxDLJ+6OEBLRHAyhEzzVi5lh/olJz17D/Zr9IYnHAQaRC0n5Z+AqRwZOmdjqEY168hTRRc4vlmIrlfSSDMTOs6jfvYWbX5VoGSPZDf2VqZTQG7pM61cLzye4KbTDnriOewZjT0YnYHgB9ogOV/D3PJKiWtgdE9sK6lq4a6ooDs+nMtubv7VhGChNGaJ+mQDUbvvv50fTtyfCF3DPCtOxX3cq+iTVo7Hti2/tQonXZnMBkmHnTXgpFI5e6wQ/MUfeXk1aU+wQptgv0UAyAd8NJzSgB4fszoewY4HR2t3wtWxpVvpBDIxTtTS5eDN+7EQzuYdS+7JrcEyriTPfAG4CT7cn8+H43se4qBLd4UiRr/zlt1EKX6tqp8dagf7eh+CAnEVWbSFO4OQghxnpzfgEQkVfwGEGg1P13Hq2xmw9qtxTXWDodFA7/4G818FYg0gHfkMCydlAG0jxuaLgtOqS3oVNb8Tth0EIwGO3Fc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
