appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: D1ub2Oawn/i0mddyIezgAM3gbJSrqTND9Bdl+P1MT/Yn17EJQVWwMo7kP5ATdPHb7NIjMmuSsA4iPFmr53gC5Y7ivC5Rg+Rjed8rC+fx0xg3Ynnekp8BB3WFK44nSjiRgfZWfaw1FkKaj5e1dxnAuFwSRgt79utjaZ7A5pfEdWBalLtcnxt2dLiChmQle+2jiRHzGHxDLJ+6OEBLRHAyhEzzVi5lh/olJz17D/Zr9IYnHAQaRC0n5Z+AqRwZOmdjqEY168hTRRc4vlmIrlfSSDMTOs6jfvYWbX5VoGSPZDf2VqZTQG7pM61cLzye4KbTDnriOewZjT0YnYHgB9ogOV/D3PJKiWtgdE9sK6lq4a6ooDs+nMtubv7VhGChNGaJ+mQDUbvvv50fTtyfCF3DPCtOxX3cq+iTVo7Hti2/tQonXZnMBkmHnTXgpFI5e6wQ/MUfeXk1aU+wQptgv0UAyAd8NJzSgB4fszoewY4HR2t3wtWxpVvpBDIxTtTS5eDN+7EQzuYdS+7JrcEyriTPfAG4CT7cn8+H43se4qBLd4UiRr/zlt1EKX6tqp8dagf7eh+CAnEVWbSFO4OQghxnpzfgEQkVfwGEGg1P13Hq2xmw9qtxTXWDodFA7/4G818FYg0gHfkMCydlAG0jxuaLgtOqS3oVNb8Tth0EIwGO3Fc=}
